apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-deployment
  ports:
  - protocol: TCP
    port: 3011
    targetPort: 3011
    nodePort: 30011